CREATE SEQUENCE SEQ_CLIENTE START WITH 1 INCREMENT BY 1;


CREATE TABLE CLIENTE (
    ID_CLIENTE INT AUTO_INCREMENT NOT NULL,
    ID_ENDERECO INT NOT NULL,
    CPF VARCHAR(15) UNIQUE,
    NOME VARCHAR(50) NOT NULL,
    SEXO ENUM('M', 'F'),
    EMAIL VARCHAR(30) UNIQUE NOT NULL,
    PRIMARY KEY (ID_CLIENTE)
);
