CREATE SEQUENCE SEQ_ENDERECO START WITH 1 INCREMENT BY 1;

CREATE TABLE ENDERECO (
    ID_ENDERECO INT DEFAULT NEXT VALUE FOR SEQ_ENDERECO NOT NULL,
    RUA VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    COMPLEMENTO VARCHAR(50),
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(2) NOT NULL,
    CEP VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID_ENDERECO)
);

