CREATE SEQUENCE SEQ_ITEM_PEDIDO START WITH 1 INCREMENT BY 1;

CREATE TABLE ITEM_PEDIDO (
    ID_ITEM_PEDIDO INT DEFAULT NEXT VALUE FOR SEQ_ITEM_PEDIDO NOT NULL,
    ID_PEDIDO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    OBSERVACAO VARCHAR(50),
    PRIMARY KEY (ID_ITEM_PEDIDO),
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);
