CREATE SEQUENCE SEQ_MOTORISTA START WITH 1 INCREMENT BY 1;


CREATE TABLE MOTORISTA(
ID_MOTORISTA INT DEFAULT NEXT VALUE FOR SEQ_MOTORISTA NOT NULL,
NOME VARCHAR(50) NOT NULL,
CNH VARCHAR(9) NOT NULL,
TELEFONE VARCHAR(11) NO NULL,
PRIMARY KEY(ID_MOTORISTA)
);