CREATE SEQUENCE SEQ_PEDIDO START WITH 1 INCREMENT BY 1;

CREATE TABLE PEDIDO(
ID_PEDIDO INT DEFAULT NEXT VALUE FOR SEQ_PEDIDO NOT NULL,
ID_CLIENTE INT NOT NULL,
ID_MOTORISTA INT NOT NULL,
ID_ROTA INT NOT NULL,
STATUS VARCHAR(20) NOT NULL,
DATA DATE NOT NULL,
PRIMARY KEY (ID_PEDIDO),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
FOREIGN KEY (ID_MOTORISTA) REFERENCES MOTORISTA(ID_MOTORISTA),
FOREIGN KEY (ID_ROTA) REFERENCES ROTA(ID_ROTA)
);