CREATE SEQUENCE SEQ_PRODUTO START WITH 1 INCREMENT BY 1;


CREATE TABLE PRODUTO (
    ID_PRODUTO INT DEFAULT NEXT VALUE FOR SEQ_PRODUTO NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    CATEGORIA VARCHAR(20) NOT NULL,
    TEMPERATURA_IDEAL VARCHAR(20) NOT NULL,
    PESO VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID_PRODUTO)
);
