CREATE SEQUENCE SEQ_ROTA START WITH 1 INCREMENT BY 1;


CREATE TABLE ROTA (
    ID_ROTA INT DEFAULT NEXT VALUE FOR SEQ_ROTA NOT NULL,
    ORIGEM VARCHAR(50) NOT NULL,
    DESTINO VARCHAR(50) NOT NULL,
    DISTANCIA VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_ROTA)
);
