CREATE SEQUENCE SEQ_VEICULO START WITH 1 INCREMENT BY 1;


CREATE TABLE VEICULO (
    ID_VEICULO INT DEFAULT NEXT VALUE FOR SEQ_VEICULO NOT NULL,
    ID_MOTORISTA INT NOT NULL,
    PLACA VARCHAR(10) UNIQUE NOT NULL,
    MODELO VARCHAR(50) NOT NULL,
    MARCA VARCHAR(50) NOT NULL,
    ANO INT NOT NULL,
    COR VARCHAR(20) NOT NULL,
    CAPACIDADE_CARGA DECIMAL(10, 2) NOT NULL,
    TIPO VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID_VEICULO),
    FOREIGN KEY (ID_MOTORISTA) REFERENCES MOTORISTA(ID_MOTORISTA)
);
